version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn package
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run:
        name: Uploading jar to SF
        command: curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'; sudo dpkg -i cf-cli_amd64.deb; cf -v; cf api https://api.run.pivotal.io; cf auth girija.behera@siemens.com S!emens123^; cf target -o Siemens-EPMS -s staging; cf a; cf push epms-ui -p ~/repo/target/epms-ui-0.0.1-SNAPSHOT.jar;
