version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    #- run: mvn integration-test
    - run: curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - run: sudo dpkg -i cf-cli_amd64.deb
    - run: cf -v
    - run: cf api https://api.run.pivotal.io
    - run: cf auth girija.behera@siemens.com S!emens123^
    - run: cf target -o Siemens-EPMS -s staging
    - run: cf a
    - run: cf push epms-ui
