version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn install
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: 
        name: Create epms-ui jar
        command: |
          mkdir /tmp/artifacts;
          
    - store_artifacts:
          path: epms-ui-0.0.1-SNAPSHOT.jar
          destination:  /tmp/artifacts
