dependencies:
  pre:
    - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
    - sudo dpkg -i cf-cli_amd64.deb
    - cf -v

test:
  post:
    - cf api https://api.run.pivotal.io
    - cf auth girija.behera@siemens.com S!emens123^
    - cf target -o girija.behera@siemens.com -s development
    - cf a

deployment:
  production:
    branch: master
    commands:
      - cf push
