version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: /tmp
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-
    - run: mvn package
    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run:
        name: Create epms-ui jar
        command: |
          mkdir /tmp/artifacts;
    - store_artifacts:
        path: /tmp/artifact-1
        destination: artifact-file
    - store_artifacts:
        path: /tmp/artifacts
